/**
 * TỰ SINH bởi `apps/seller/scripts/capture-order-guide.mjs` — KHÔNG sửa tay, chạy lại script để cập nhật.
 * Toạ độ theo % ảnh, lấy từ boundingBox thật của phần tử (xem OrderGuide.md §3, §6).
 */

import type { GuideShot } from './guideTypes';

export const GUIDE_SHOTS = {
  'form-01-login': {
    file: 'form-01-login.webp',
    width: 448,
    height: 512,
    callouts: [
      { n: 1, xPct: 50, yPct: 55, boxPct: { x: 11.6, y: 46.2, w: 76.8, h: 13.8 } },
      { n: 2, xPct: 50, yPct: 69.1, boxPct: { x: 11.6, y: 60.4, w: 76.8, h: 13.8 } },
      { n: 3, xPct: 50, yPct: 84.9, boxPct: { x: 11.6, y: 80, w: 76.8, h: 9.8 } },
    ],
    ink: {
      cell: 12,
      cols: 38,
      rows: 43,
      data: 'AAAAAAAAAAAAAAD4AwAAAP4AAACAPwAAAOAPAAAA+AMAAAD+AAAAgD8AAADgDwAA+P//AwD+//8AgP//PwDg//8PAPD//wMA/P//AAAAAAAAAAAAAAAAAAAAAAAAAADwAAAAAPz//38A////H8D///8H8P///wH8//9/AD8AAADA////B/D///8B/P//fwD///8fwP///wfw/wAAAPw/AAAAAAAAAAAA/gAAAIA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPx/AAAA/x8AAA==',
    },
  },
  'form-02-choose-line': {
    file: 'form-02-choose-line.webp',
    width: 1440,
    height: 900,
    callouts: [
      { n: 1, xPct: 7.3, yPct: 17.4, boxPct: { x: 0.1, y: 15.2, w: 14.4, h: 4.4 } },
      { n: 2, xPct: 7.3, yPct: 24.5, boxPct: { x: 0.1, y: 22.3, w: 14.4, h: 4.4 } },
      { n: 3, xPct: 91.1, yPct: 6.2, boxPct: { x: 84.7, y: 3.7, w: 12.9, h: 4.9 } },
      { n: 4, xPct: 80.5, yPct: 6.2, boxPct: { x: 76.2, y: 3.6, w: 8.7, h: 5.1 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 75,
      data: 'AAAAAAAAAAAAAAAAAAAA/ocBAAAAAAAAAAAAAAAA/ocB/h8AAAAAAAAAAAAA/gPg/h8AAAAAAADAH/8PAADg/h8AAAAAAADgn/8PPgDg/h8AAAAAAADgn/8PPgAA/h8AAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gDwAQAfAPAHAP8A8AEA/gDwARgfgPEHGP+A8QEY/gAwABgBgBEAGAGAEQAY/oExAAABABAAAAEAEAAA/oEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//9/PADw/fn5+3m+xw/A//9/PADw/fn5+3m+xw/A//9//AcAAAAAAAAAAADA//9//AcAAAAAAAAAAAAAAAAAHACAH8APAAB/+OPPnx8APACAH8APAAB/+OPPnx8APAAAAAAAAAAAAAAAAAAAAACY/8P////++cfPAJ4bfACY/8P////++cfPAJ4bfACA/8///wAA+AcAAAAAfACA/88DAAAAAAAAAAAAfACA/wcAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAA/AAYAMD//z/++cPPAB4A/ACY/8P//z/++c/PAJ4bAACY/8///wAA+A/AAIAbPgCA/88DAAAA+A8AAAAAPgCA/wcAAAAAAAAAAAAA/gCA/wcAAAAAAAAAAAAA/gAAAMD//z8A+AEAAB4A/geY/8P//z/++cHPAJ4b/geY/8P//z/++cPPAJ4bAACA/8P/AQAA+AMAAAAA/gOA/8MDAAAAAAAAAAAA/gMAAAAAAAAAAAAAAAAAAACA/8P//z/++cHPAB4AAACA/8P//z/++cPPAB4AAACA/8P/AQAA+OMPAAAAAACA/8MDAAAAAOAPAAAAAAAAAAAAAAAAAAAAAAAAAACA/8P//z/++cPPAB4AAACA/8P//z/++c/PAB4AAACA/8///wAA+O8PAAAAAACA/88DAAAAAOAPAAAAAACA/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMD////++cfPAB4AAACA/8P////++cfPAB4AAACA/8///wAA+OfPAAAAAACA/88DAAAA+OcPAAAAAACA/wcAAAAAAAAAAAAAAACA/wcAAAAAAAAAAAAAAAAAAMD///8A+AcAAB4AAACA/8P////++cfPAB4AAACA/8/////++cfPAB4AAACA/8///wAA+OcPAAAAAACA/88DAAAAAOAPAAAAAACA/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA/8D//z/++cHPAB4AAACA/8P//z/++cPPAB4AAACA/8P/AQAA+OPPAAAAAACA/8MDAAAAAOAPAAAAAAAAAAAAAAAAAAAAAAAADvYAAAAAAAAAAAAAAAAADvbw/w8AAAAAAAAAAAAAAADw/w8AAAAAAAAAAAAA/oHx/w8AAAAAAAAAAAAA/oGB/wcAAAAAAAAAAAAAeACA/wcAAAAAAAAAAAAA',
    },
  },
  'form-03-pick-product': {
    file: 'form-03-pick-product.webp',
    width: 1440,
    height: 1120,
    callouts: [
      { n: 1, xPct: 32.8, yPct: 5.5, boxPct: { x: 16.9, y: 3.8, w: 31.7, h: 3.4 } },
      { n: 2, xPct: 37.2, yPct: 80.2, boxPct: { x: 30.5, y: 66.9, w: 13.4, h: 26.7 } },
      { n: 3, xPct: 84.7, yPct: 12.2, boxPct: { x: 73.1, y: 10.8, w: 23.1, h: 2.7 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 94,
      data: 'AAAAAAAAAAAAAAAAAAAA/ofBHwAAAAAAAAAAAAAA/ofxHwAAAAAAAAAAAAAA/gPwHwAAAAAAAAAAAAAAAADw//8DAAAAAAAAAAAAPgDw//8DAAAAAAAAAAAAPgDw/////wMAAAAAAAAA/gDw/////wMAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gDwPwAAAPD//x8AAAAA/gDwPwAAAPD//x//PwAA/gDwPwAAAPD//x//PwAA/oHx/+////8fAAD/PwAA/oHx/+////8fAAD///8DAADw/+////8fAAD///8DPADw/+////8fAAAPAAAAPADw/+////8fAAAAAAAA/Afw/+////8fAAAAAAAA/Afw/+////8fAAAAAAAAHADw/+////8fcAAAAAAAPADw/+////8fcAD/AwAAPADw/+////8fcAD/AwAAAADw/+////8fAAAH4AAAfADw/+////8fAAAH4AAAfADw/+////8fAAD///8HfADw/+////8fAAD///8HfADw/+////8fAAD///8HHADw/+////8fAAAPAAAA/ADAAMAPwAvABwAPAAAA/ADAAMAPwAvAHwD///8HAADg/8f/w//DHwD///8HPgDg/8f/w//DDwD///8HPgDg/8N/wP/BDwD///8H/gDg/8N/wP/BAwD/AAAA/gDgw8eDz4fPgw////8H/gfgw8eDz4fPgw////8H/gcAAAAAAAAAAAD///8HAADw/+///////x////8H/gPw/+///////x8PAAAA/gPw/+///////x////8HAADw/+///////x////8HAADw/+///////x////8HAADw/+///////x////8HAADw/+///////x//4Q8AAADw/+///////x////8HAADw/+///////x////8HAADw/+///////x////8HAADw/+///////x////8HAADw/+///////x8/AAAAAADw/+///////x//PwAAAADw/+///////x//PwAAAADw/+///////x//PwAAAADw/+///////x//PwAAAADgA8ADwAPABwAfAAAAAADgD8APwAvAHwD///8HAADg/8f/wf/P/w////8HAADg/8f/wf/P/w////8HAADg/8f/z//H/wD///8HAADg/8f/z//H/wB/4AEAAADgw8eDz4fPhw////8HAADgw8eDz4fPhw////8HAAAAAAAAAAAAAAD///8HAADw/+//HwAAAAD///8HAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADw/+//HwAAAAAAAAAAAADgA8ADAAAAAAAPAAAAAADgD8APAAAAAAAPAAAAAADg/8D/DwAAAAD///8PAADg/8D/DwAAAAD///8PAADg/8H/DwAAAAD///8PAADg/8EfAAAAAAD///8PAADgw8fDDwAAAAD///8PAADgw8fDDwAAAAD///8PAAAAAAAAAAAAAAAAAAAADvYAAAAAAAAAAAAA/w8ADvYAAD8AAAAAAAAA/w8AAADA/z8AAAAAAAAA/w8A+IHB/z8AAAAAAAAAAAAA/oEBAAAAAAAAAAAAAAAAeIABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    },
  },
  'form-04-variant': {
    file: 'form-04-variant.webp',
    width: 800,
    height: 448,
    callouts: [
      { n: 1, xPct: 54.8, yPct: 9.7, boxPct: { x: 13, y: 6.3, w: 83.5, h: 6.7 } },
      { n: 2, xPct: 29.4, yPct: 37.7, boxPct: { x: 25.2, y: 33, w: 8.5, h: 9.4 } },
      { n: 3, xPct: 16.9, yPct: 68.7, boxPct: { x: 14, y: 64, w: 5.8, h: 9.4 } },
      { n: 4, xPct: 50, yPct: 92.6, boxPct: { x: 3.5, y: 83.4, w: 93, h: 14.1 } },
    ],
    ink: {
      cell: 12,
      cols: 67,
      rows: 38,
      data: 'AAAAAAAAAAAAAAAAAAAAAAD///8/AAAAAPj///8BAAAAwP///w8AAAAA/v8BAAAAAADwfwAAAAAAAID/AwAAAAAAAPz/AQAAAAAAAPAPAAAAAAAAHwAAAAAAAAD4AAAAAAAAAMAHAAAAAAAAALx/3r97fz8A4P3z/t37+wEAAAAAAAAAAAD47z0/3+/3fMB/7/n5fr/nAwAAAAAAAAAA8Hf/e/4HAACAv/vf8z8AAAD83f+e/wEAAPABAAAAAAAAgA8AAAAAAAAAmMnu7gAAAADATHZ3BwAAAABmsrs7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAPAAAAAAAAAHwAAAAAAAAA4P////////8H/////////z/4/////////wEAAAAAAAAAAP4fAAAAAAAAAA==',
    },
  },
  'form-05-files': {
    file: 'form-05-files.webp',
    width: 800,
    height: 460,
    callouts: [
      { n: 1, xPct: 47.3, yPct: 44.5, boxPct: { x: 3.5, y: 30.5, w: 87.5, h: 19 } },
      { n: 2, xPct: 47.3, yPct: 61, boxPct: { x: 3.5, y: 51.9, w: 87.5, h: 14.1 } },
      { n: 3, xPct: 50, yPct: 88.9, boxPct: { x: 3.5, y: 83.9, w: 93, h: 10 } },
    ],
    ink: {
      cell: 12,
      cols: 67,
      rows: 39,
      data: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAwP////////8P/v///////3/w/////////4P/////////H/w/AAAAAAAA4P8BAAAAAAAA/w8AAAAAAAAAAAAAAAAAAMA/AAAAAAAAAP7///9/AAAA8P////8DAACA/////////wP8/////////+D/////////B/////////8HAAAAAAAAAADA//8BAAAAAAD+////////D/D/////////g/////////8f/P////////8AAAAAAAAAAAD//wcAAAAAAPj/PwAAAAAAwP////////8B/v///////3/w/////////4P/////////AwAAAAAAAAAAAAAA4P8HAAAAAAAA/z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    },
  },
  'form-06-cart-address': {
    file: 'form-06-cart-address.webp',
    width: 380,
    height: 740,
    callouts: [
      { n: 1, xPct: 50, yPct: 21.1, boxPct: { x: 6.3, y: 15.6, w: 87.4, h: 8.5 } },
      { n: 2, xPct: 28.3, yPct: 70.6, boxPct: { x: 6.3, y: 65, w: 43.9, h: 8.5 } },
      { n: 3, xPct: 50.5, yPct: 86.6, boxPct: { x: 6.3, y: 78.9, w: 88.4, h: 12.8 } },
      { n: 4, xPct: 50.5, yPct: 95.9, boxPct: { x: 6.3, y: 92.8, w: 88.4, h: 6.2 } },
    ],
    ink: {
      cell: 12,
      cols: 32,
      rows: 62,
      data: 'AAAAAAAAAAD8DwAA/A8AAPwPAwAcAAMA/P//P/z//z/8//8//P//P3wAAAD8//8//P//P/z//z/8//8//AMAAPz//z/8//8//P//P/z//z88AAAA/P//P/z//z/8//8//P//P/wHPwD8//8//P//P/z//z/8//8//AAAAPz/AAD8/wAA/P8AAPz/AAB8AAAAfAAAAPz//z/8//8//P//P/wBBwD8AQcA/P//P/z//z/8//8/AAAAAAAAAAAAAAAAAAAAADwAAAD8//8//P//P/z//z/8//8//P//P/z//z/8//8/AAAAAAD8PwAA/D8AAAAAAAAAAAA=',
    },
  },
  'form-07-pending': {
    file: 'form-07-pending.webp',
    width: 1440,
    height: 900,
    callouts: [
      { n: 1, xPct: 24.6, yPct: 21.3, boxPct: { x: 21.2, y: 19.2, w: 6.9, h: 4.1 } },
      { n: 2, xPct: 23.1, yPct: 31.3, boxPct: { x: 19.3, y: 29.8, w: 7.6, h: 2.9 } },
      { n: 3, xPct: 73.1, yPct: 30.9, boxPct: { x: 70.2, y: 29.2, w: 5.8, h: 3.4 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 75,
      data: 'AAAAAAAAAAAAAAAAAAAA/ocBAAAAAAAAAAAAAAAA/ocB/h8AAAAAAAAAAAAA/gPg/h8AAAAAAADAH/8PAADg/h8AAAAAAADgn/8PPgDg/g8AAAAAAADgn/8PPgAA/g8AAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gDwAQAfAPAHAP8A8AEA/gDwARgfgPEHGP+A8QEY/gAwABgBgBEAGAGAEQAY/oExAAABABAAAAEAEAAA/oEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//9/PADw/f35+Xmexw/A//9/PADw/f35+Xmexw/A//9//AcAAAAAAAAAAADA//9//AcAAAAAAAAAAAAAAAAAHACYH/ADAAB/+PPjjw8APACYH/ADAAB/+PPjjw8APAAAAAAAAAAAAAAAAAAAAACY//D//w//+OFnAI8bfACY//P//w//+ONnAI8bfACA//N/AAAA+ANgAIAbfACA//MBAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gcAAAAAAAAAAAAAAAAA/gcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gMAAAAAAAAAAAAAAAAA/gMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvYAAAAAAAAAAAAAAAAADvbw/wcAAAAAAAAAAAAAAADw/wcAAAAAAAAAAAAA/oHx/wcAAAAAAAAAAAAA/oEBAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAA',
    },
  },
  'push-01-select': {
    file: 'push-01-select.webp',
    width: 1440,
    height: 900,
    callouts: [
      { n: 1, xPct: 24.7, yPct: 21.3, boxPct: { x: 21.2, y: 19.2, w: 7, h: 4.1 } },
      { n: 2, xPct: 17, yPct: 52.6, boxPct: { x: 16.3, y: 51.3, w: 1.6, h: 2.6 } },
      { n: 3, xPct: 18.9, yPct: 25.8, boxPct: { x: 15.6, y: 23.7, w: 6.6, h: 4.2 } },
      { n: 4, xPct: 93.7, yPct: 52.9, boxPct: { x: 92, y: 51.1, w: 3.4, h: 3.7 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 75,
      data: 'AAAAAAAAAAAAAAAAAAAA/ocBAAAAAAAAAAAAAAAA/ocB/h8AAAAAAAAAAAAA/gPg/h8AAAAAAADAH/8PAADg/h8AAAAAAADgn/8PPgDg/g8AAAAAAADgn/8PPgAA/g8AAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gDwAQAfAPAHAP8A8AEA/gDwARgfgPEHGP+A8QEY/gAwABgBgBEAGAGAEQAY/oExAAABABAAAAEAEAAA/oEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//9/PADw/fn5+3m+xw/A//9/PADw/fn5+3m+xw/A//9//AcAAAAAAAAAAADA//9//AfwAwAAAAAAAAAAAAAAHADwAwAAAAAAAAAAAAAAPADwAwAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAACYH8APAAB/+OPPnx8AfACYH8APAAB/+OPPnx8AfAAAAAAAAAAAAAAAAAAAfAAAAMD////8+ccPAB4AfACY/8P////++cfPAJ4bHACY/8///wD8+cfPAIAb/ACA/8///wAA+AcAAAAA/ACA/wcAAAAAAAAAAAAAAACA/wcAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAPgCY/8P//z/++cPPAJ4b/gCY/8P//z/++c/PAJ4b/gCA/8///wAA+A8AAAAA/geA/88DAAAAAAAAAAAA/geA/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gMYAMD//z/++cHPAB4A/gOY/8P//z/++cPPAJ4bAACA/8P/AQAA+APAAIAbAACA/8MDAAAA+AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvYAAAAAAAAAAAAAAAAADvbw/wcAAAAAAAAAAAAAAADw/wcAAAAAAAAAAAAA/oHx/wcAAAAAAAAAAAAA/oEBAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAA',
    },
  },
  'push-02-dialog': {
    file: 'push-02-dialog.webp',
    width: 736,
    height: 462,
    callouts: [
      { n: 1, xPct: 19.8, yPct: 12.4, boxPct: { x: 6.5, y: 9.2, w: 26.7, h: 6.5 } },
      { n: 2, xPct: 80.5, yPct: 33.1, boxPct: { x: 67.6, y: 27.5, w: 25.8, h: 11.2 } },
      { n: 3, xPct: 25.6, yPct: 87.9, boxPct: { x: 6.5, y: 84.6, w: 38.2, h: 6.5 } },
      { n: 4, xPct: 82.9, yPct: 86.3, boxPct: { x: 72.3, y: 81.3, w: 21.2, h: 10 } },
    ],
    ink: {
      cell: 12,
      cols: 62,
      rows: 39,
      data: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA/z8AAAAAAPD/DwAAAIAB/P8DAAAAYAAAAAAAAAAAAAAAAAAAAADgHwAAAADwAPgHAAAAADwA/gEAAAAAD4D//x8AAAAA4P//B8AA/wD4DwAAMMA/AAAAAAAAAAAAAAAAAAAAAOAfAAAAAPAA+AcAAAAAPAD+/x8AAAAAgP//BwAD/APg//8BwAD/APgPAAAAAAAAAAAAAAAAAIAPAAAAAMAD4AMAAAAA8AD4AAAAAAA8AP7/HwAM8A+A//8HAAP8AyAAAADAAP8AAAAAAAAAAAAAAAAAAAAAwP//HwAAAADw//8HAMD/APwfAAAA8D8A/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    },
  },
  'push-03-status': {
    file: 'push-03-status.webp',
    width: 1440,
    height: 900,
    callouts: [
      { n: 1, xPct: 30.6, yPct: 21.3, boxPct: { x: 27, y: 19.1, w: 7.2, h: 4.3 } },
      { n: 2, xPct: 78.3, yPct: 30.6, boxPct: { x: 75.5, y: 28.9, w: 5.5, h: 3.4 } },
      { n: 3, xPct: 78.1, yPct: 33.1, boxPct: { x: 75.5, y: 31.7, w: 5.1, h: 2.8 } },
      { n: 4, xPct: 23.1, yPct: 31.1, boxPct: { x: 19.3, y: 29.6, w: 7.6, h: 2.9 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 75,
      data: 'AAAAAAAAAAAAAAAAAAAA/ocBAAAAAAAAAAAAAAAA/ocB/h8AAAAAAAAAAAAA/gPg/h8AAAAAAADAH/8PAADg/h8AAAAAAADgn/8PPgDg/h8AAAAAAADgn/8PPgAA/h8AAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gDwAQAfAPAHAP8A8AEA/gDwARgfgPEHGP+A8QEY/gAwABgBgBEAGAGAEQAY/oExAAABABAAAAEAEAAA/oEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA//9/PADw/f78/D7P4wfA//9/PADw/f78/D7P4wfA//9//AcAAAAAAAAAAADA//9//AcAAAAAAAAAAAAAAAAAHACAH4AfAADwB3/48cMHPACAH4AfAADwB3/48cMHPAAAAAAAAAAAAAAAAAAAAACA/4P//3/wDx/4MYAHfACA/4P//3/wDz/4MYAHfACA/4P/AwAAAD/4AQAAfACA/4MPAAAAAAD4AQAAfAAAAAAAAAAAAAAAAAAAHACA/4P//3/wD3/4MYAH/ACA/4P//3/wD//4MYAH/ACA/4///wEAAP/4AQAAAACA/48PAAAAAAD4AQAAPgCA/wcAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAA/gAAAID////BD3/4AYAH/gCA/4P////xD3/4MYAH/geA/4///wPAD3/4MQAA/geA/4///wMAAH/4AQAAAACA/wcAAAAAAAAAAAAA/gOA/wcAAAAAAAAAAAAA/gMAAAAAAAAAAAAAAAAAAACA/4P//3/wDx/4MYAHAACA/4P//3/wDz/4MYAHAACA/4P/AwAAAD/4AQAAAACA/4MPAAAAAAD4AQAAAAAAAAAAAAAAAAAAAAAAAACA/4P//3/wD3/4MYAHAACA/4P//3/wD//4MYAHAACA/4///wEAAP/4AQAAAACA/48PAAAAAAD4AQAAAACA/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAID////xD3/4MYAHAACA/4P////xD3/4MYAHAACA/4///wMAAH/4MQAAAACA/48PAAAAAH/4AQAAAACA/wcAAAAAAAAAAAAAAACA/wcAAAAAAAAAAAAAAAAAAID///8BAH8AAIAHAACA/4P////xD3/4MYAHAACA/4/////xD3/4MYAHAACA/4///wMAAH/4AQAAAACA/48PAAAAAAD4AQAAAACA/wcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACA/4D//3/wDx/4MYAHAACA/4P//3/wDz/4MYAHAACA/4P/AwAAAD/4MQAAAACA/4MPAAAAAAD4AQAAAAAAAAAAAAAAAAAAAAAADvYAAAAAAAAAAAAAAAAADvbw/w8AAAAAAAAAAAAAAADw/w8AAAAAAAAAAAAA/oHx/w8AAAAAAAAAAAAA/oGB/wcAAAAAAAAAAAAAeACA/wcAAAAAAAAAAAAA',
    },
  },
  'push-04-detail': {
    file: 'push-04-detail.webp',
    width: 1440,
    height: 1080,
    callouts: [
      { n: 1, xPct: 25.3, yPct: 6.4, boxPct: { x: 15.6, y: 4.7, w: 19.3, h: 3.5 } },
      { n: 2, xPct: 43.3, yPct: 14.5, boxPct: { x: 17.4, y: 12.7, w: 51.9, h: 3.5 } },
      { n: 3, xPct: 77.5, yPct: 32.4, boxPct: { x: 73.2, y: 31.1, w: 8.6, h: 2.5 } },
      { n: 4, xPct: 93.7, yPct: 67.9, boxPct: { x: 90.1, y: 66, w: 7.1, h: 3.7 } },
      { n: 5, xPct: 75.4, yPct: 92, boxPct: { x: 73.2, y: 90.6, w: 4.4, h: 2.8 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 90,
      data: 'AAAAAAAAAAAAAAAAAAAA/ofxBwAAAAAAAAAAAAAA/of5BwAAAAAAAAAAAAAA/gP4BwAAAAAAAAAAAAAAAAD4/wEAAAAAAAAAAAAAPgD4/wEAAAAAAAAAAOBvPgD4/wEAAAAAAAAAAOBv/gD4//8DAAAAAAAAAOBv/gD4//8DAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAA/oHh/wMAAAAAAAD/AwAA/oHh/wMAAAAAAAD/AwAAAADg/wMAAAAAAAD/AwAAPgAAAAAAAAAAAAAAAAAAPgAAfwAAAAAAAAAPAAAA/gBgfwAAAAAAAAAPAAAA/gBgfwAAAAAAAAD/AAAA/gcADwAAAAAAAAD/AAAA/gcADwAAAAAAAAB/AAAAAABgDwAAAAAAAAD/AAAA/gNgDwAAAAAAAAD/AAAA/gMADwAAAAAAAAB/AAAAAABgAwAAAAAAAAB/AAAAAABgDwAAAAAAAAB/AAAAAAAADwAAAAAAAAD/BwAAAAAAAwAAAAAAAAD/BwAAAABgAwAAAAAAAAD/DwAAAABgDwAAAAAAAAD/DwAAAAAADwAAAAAAAAAAAAAAAABg/wAAAAAAAAAAAAAAAABg/wAAAAAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAfwAAAAAAAAAAAAAAAABgfwAAAAAAAAA/AAAAAABgfwAAAAAAAAA/AAAAAAAADwAAAAAAAAA/AAAAAABgPwAAAAAAAAAAAAAAAABgPwAAAAAAAAAAAAAAAAAADwAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAABgPwAAAAAAAAD///8fAABgPwAAAAAAAAD///8fAAAADwAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAADg/w8AAAAAAAD///8fAADg/w8AAAAAAAD///8fAADg/w8AAAAAAAD///8fAAAAAAAAAAAAAAD///8fAAAAAAAAAAAAAAD///8fAADg//8BAAAAAAD///8fAADg//8BAAAAAAD///8fAADg//8BAAAAAAD///8fAADg//8BAAAAAAD///8fAADg//8BAAAAAAD//+8PAADg//8BAAAAAAD//+8PAADg//8BAAAAAAD//w8AAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAD/HwAAAADg//8BAAAAAAD/HwAAAADg//8BAAAAAAD/HwAAAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAAAAAAAAADg//8BAAAAAAA/AAAAAADg//8BAAAAAAD/AAAAAADg//8BAAAAAAD/AAAAAADAAQAAAAAAAAD/AAAAAADAAQAAAAAAAAD/AAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAD//wMAAAAAAAAAAAAAAAD//wMAAAAAAAAAAAAAAAD//wMAAAAAAAAAAAAAAAAfAAAAAAAAAAAAAAAAAAAfAAAADvYAAAAAAAAAAAAAAAAADvYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/oEBAAAAAAAAAAAAAAAA/oEBAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAA',
    },
  },
  'push-05-track': {
    file: 'push-05-track.webp',
    width: 1440,
    height: 900,
    callouts: [
      { n: 1, xPct: 81.7, yPct: 11.3, boxPct: { x: 78.7, y: 8.4, w: 6.1, h: 5.8 } },
      { n: 2, xPct: 23.5, yPct: 23.1, boxPct: { x: 16.9, y: 20.9, w: 13.1, h: 4.2 } },
      { n: 3, xPct: 38.3, yPct: 38.6, boxPct: { x: 16.9, y: 36.4, w: 42.8, h: 4.2 } },
    ],
    ink: {
      cell: 12,
      cols: 120,
      rows: 75,
      data: 'AAAAAAAAAAAAAAAAAAAAAAD8fwAAAAAAAAD4PwAAAAD8fwAAAAAAAAD4PwAAAAD8DwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8//////////9/AAAAAAD8//////////9/DwAAAAD8//////////9/DwAAAAD8//////////9/DwAAAAD8//////////9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwBwAAAAAAAODfBwAAAADw/w8AAAAAAODfBwAAAADw/w8AAAAAAAAAAAAAAADw/wMAAAAAAAAAAAAAAADwDwAAAAAAAAAAAAAAAADwDwAAAAAAAAAAAAAAAADwDwAAAAAAAAAAAAAAAADwDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/wMAAAAA8A8AAAAAAADw/wMAAAAA8A8AAAAAAADw/wMAAAAA8A8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAfwAAAAAA8P//DwAAAADgfwAAAAAA8P//DwAAAADgfwAAAAAA8P//DwAAAACADwAAAAAA8P//DwAAAADgDwAAAAAA8P//DwAAAADgDwAAAAAA8P//DwAAAACABwAAAAAA8P//DwAAAAAAAAAAAAAA8P//DwAAAADgAQAAAAAA8P//DwAAAADgBwAAAAAA8P//DwAAAACABwAAAAAA8P//DwAAAACAAQAAAAAA8P//DwAAAADgBwAAAAAA8P//DwAAAADgBwAAAAAA8P//DwAAAACABwAAAAAA8P//DwAAAADgfwAAAAAA8P//DwAAAADgfwAAAAAA8P//DwAAAACABwAAAAAA8AEfAAAAAACAfwAAAAAA8D8fAAAAAADgfwAAAAAA8D8BAAAAAADgfwAAAAAA8H8BAAAAAACABwAAAAAA8H8AAAAAAADgPwAAAAAAcAAPAAAAAADgPwAAAAAA8AAPAAAAAACABwAAAAAA8AABAAAAAACAHwAAAAAAAAAAAAAAAADgHwAAAAAAAAAAAAAAAADgHwAAAAAAAAAAAAAAAACABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8H8AAAAAAAAAAAAAAAAA8H8AAAAAAAAAAAAAAAAA8H8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADw/wEAAAAA8AEAAAAAAADw/wEAAAAA8B8AAAAAAADw/wEAAAAA8B8AAAAAAAAAAAAAAAAA8AcAAAAAAAAAAAAAAAAA8B8AAAAAAADw/x8AAAAA8B8AAAAAAADw/x8AAAAA8B8AAAAAAADw/x8AAAAA8B8AAAAA',
    },
  },
  'import-01-open': {
    file: 'import-01-open.webp',
    width: 882,
    height: 291,
    callouts: [
      { n: 1, xPct: 91.8, yPct: 24.5, boxPct: { x: 84.9, y: 18, w: 13.9, h: 13.1 } },
      { n: 2, xPct: 79.3, yPct: 24.5, boxPct: { x: 73.4, y: 17.7, w: 11.7, h: 13.7 } },
      { n: 3, xPct: 50, yPct: 72.6, boxPct: { x: 43.9, y: 66.1, w: 12.2, h: 13.1 } },
    ],
    ink: {
      cell: 12,
      cols: 74,
      rows: 25,
      data: 'AAAAAAAAAAAA+AcAAAAAAAAA4B8AAAAAAAAAAAAAAAAAAAAAAP7//38AAAAAAPj///8BAAD+/uP/////HwD4+4//////fwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAADgAAAAAAAAAAOAAAAAAAAAA4P//DwAAAAAAgP//PwAAAAAAAAD4AAAAAAAAAAD4AwAAAAAAAADgDwAAAAAAAPz///8PAAAAAPD///8/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==',
    },
  },
  'import-02-lookup-sku': {
    file: 'import-02-lookup-sku.webp',
    width: 780,
    height: 788,
    callouts: [
      { n: 1, xPct: 85.3, yPct: 3.6, boxPct: { x: 72.6, y: 2, w: 25.5, h: 3.2 } },
      { n: 2, xPct: 12.3, yPct: 11.4, boxPct: { x: 2, y: 8.9, w: 20.5, h: 5 } },
      { n: 3, xPct: 12.3, yPct: 16.3, boxPct: { x: 2, y: 12.7, w: 20.5, h: 7.3 } },
    ],
    ink: {
      cell: 12,
      cols: 65,
      rows: 66,
      data: 'AAAAAAAAAAD8HwAAAAD///k/AAAAAP7/838AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAQDgfT4fBuADAMD7fD4AAAAAAAAAAACA/wcAz8Ph8B//DwCeh/PhP/4fADwP5wMAAAAAAAAAAAD4/wfwPBwO//H/D+B5OB/+4/8fwPNwPgAAAAAAAAAAAID/DwDPw+HwH/8fAJ6H8+E//j8APA/nAwAAAAAAAAAAAPj/B/A8HA7/8f8P4Hk4H/7j/x/A83A+AAAAAAAAAAAAgP8HAM/D4fAf/w8Anofz4T/+HwA8D+cDAAAAAAAAAAAA+H8A8DwcDv/x/wDgeTgf/uP/AcDzcD4AAAAAAAAAAPiD/z8Az8Ph8B//fwCeh/PhP/7/ADwP5wMAAAAAAAAAgD/4/wPwPBwO//H/B+B5OB/+4P8PwPNwPgAAAAAAAAAA+IP//wDPw+HwH///AZ6H8+EP/v8DPA/nAwAAAAAAAACAP/h/APA8HA7/8f8A4Hk4H/7g/wHA83A+AAAAAAAAAAD4g/8PAM/D4fAf/x8AnofzAQD+PwA8D+cDAAAAAAAAAIA/+P8D8DwcDv/x/wfgeTgfAOD/D8DzcD4AAAAAAAAAAPiD/x8Az8Ph8B//PwCeh/MBAAAAAAAA4AMAAAAAAAAAgD/4/wHwPBwO//H/A+B5OB8AAAAAAAAAPgAAAAAAAAAA+IP/PwDPw+EA',
    },
  },
  'import-03-preview-errors': {
    file: 'import-03-preview-errors.webp',
    width: 886,
    height: 274,
    callouts: [
      { n: 1, xPct: 15.3, yPct: 11.2, boxPct: { x: 12.2, y: 6.2, w: 6.1, h: 10 } },
      { n: 2, xPct: 84.5, yPct: 66.3, boxPct: { x: 81.5, y: 56.3, w: 6.1, h: 20.1 } },
      { n: 3, xPct: 53.5, yPct: 85.7, boxPct: { x: 41.6, y: 77.8, w: 23.7, h: 15.7 } },
      { n: 4, xPct: 90.9, yPct: 11.2, boxPct: { x: 83.5, y: 4.3, w: 14.8, h: 13.9 } },
    ],
    ink: {
      cell: 12,
      cols: 74,
      rows: 23,
      data: 'AAAAAAAAAAAA+HcAAAAAAAD4498BAAAAAAD4j38HAAAAAADgPwAAAAAAAAAAAPj///8HAAAAAOD///8fAAAAAAAAAAAAAAAAAAD8+OGA/wB+8H/z44cD/v/4wf/Njw8G+P9jAO8x////4/+f/5zf/P//j/9//nN+8///P/7/+c/7DQAAAPgfAAAPAAAAAAB/AAA8AAAAAAD8AQDwAAAAAAAAAAAAAMD////7/+f/4zf////v/5//j98AAACAfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    },
  },
  'import-04-preview-valid': {
    file: 'import-04-preview-valid.webp',
    width: 886,
    height: 256,
    callouts: [
      { n: 1, xPct: 18.5, yPct: 12, boxPct: { x: 12.2, y: 6.7, w: 12.5, h: 10.7 } },
      { n: 2, xPct: 55.2, yPct: 48.6, boxPct: { x: 45.9, y: 41.3, w: 18.7, h: 14.6 } },
      { n: 3, xPct: 90.9, yPct: 12, boxPct: { x: 83.5, y: 4.6, w: 14.8, h: 14.8 } },
    ],
    ink: {
      cell: 12,
      cols: 74,
      rows: 22,
      data: 'AAAAAAAAAAAA+PcPAAAAAAD4498/AAAAAAD4j3//AAAAAADgPwAAAAAAAAAAAODjhwP/Afzh+86PHw78B/CH7zs/Phjw/8cBvucAAADA/x8AAADw//8////9T/jP/////P/3P+E/AAAA8H8AAAAAAAAAwP8AAAAAAAAAAPADAAAAgP//////83/hP///////z/+F//z/////P/8X/gMAAAD/HwAAAAAAAADADwAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    },
  },
  'import-05-result': {
    file: 'import-05-result.webp',
    width: 882,
    height: 140,
    callouts: [
      { n: 1, xPct: 5.2, yPct: 22, boxPct: { x: 1.2, y: 12.2, w: 7.9, h: 19.5 } },
      { n: 2, xPct: 93.8, yPct: 52.7, boxPct: { x: 90.2, y: 43.4, w: 7, h: 18.6 } },
      { n: 3, xPct: 91.5, yPct: 22, boxPct: { x: 84.3, y: 8.4, w: 14.5, h: 27.1 } },
    ],
    ink: {
      cell: 12,
      cols: 74,
      rows: 12,
      data: 'AAAAAAAAAAAA8P4OAAAAAAD+w/s7AAAAAAD4D+/vAAAAAADgPwAAAAAAAAAAAPD/PwAAAAAA8MP//wAAAAAAwA8AAAAAAAAAAAD8/w8AAAAAAPzw/z8AAAAAAPADAAAAAAAAAAAAAAAAAAAAAAAA',
    },
  },
} satisfies Record<string, GuideShot>;
