/**
 * Map `OrderEntity.type` (tên sản phẩm tiếng Anh, khớp `ProductConfig.fullName`
 * lúc import) → mã ngắn cho tool duyệt thiết kế bên ngoài. Chỉ dùng ở
 * `getNextDesignReviewOrder()` — KHÔNG liên quan tới mapping xưởng/machine
 * (`productConfigId`, xem `importOrders`).
 */
const PRODUCT_TYPE_CODE_MAP: Record<string, string> = {
    "all-over print satin short-sleeve pajama shirt": "SSHIRTV",
    "all-over print satin long pajama pants - no piping": "LPJM",
    "all-over print satin short-sleeve pajama set": "SPJMV",
    "all-over print satin long pajama pants": "LPJMV",
    "all-over print v-neck soccer jersey": "TXV",
    "all-over print women's leggings": "LG",
    "all-over print satin long-sleeve pajama shirt": "SHIRTLPJMV",
    "all-over print basketball v-neck mesh shirt": "TTOPVAICOTIM",
    "all-over print string bikini": "BKNTG",
    "all-over print casual bikini set": "BKN",
    "crop top baseball jersey": "CRTOP",
    "all-over print v-neck sleeveless jersey tank top": "TTOPV",
    "all-over print sports bra": "BRA",
    "all-over print sleeveless jersey tank top": "TTOP",
    "all-over print premium women's polo shirt": "PLN",
    "women's sleeveless performance polo shirt": "PLNSN",
    "all-over print sweatpants 270 gsm": "SP270",
    "all-over print kids hoodie": "HDKIDS",
    "double-sided printed canvas flag": "CANVASFLAG",
    "all-over print women's t-shirt": "TXWOMEN",
    "all-over print and embroidered men's polo shirt": "PLNGUC",
    "all-over print chest embroidered logo men's polo shirt us tag": "PLUSTAG",
    "all-over print embroidered logo men's polo shirt": "PLTRU",
    "aop men's polo shirt with woven placket label": "PLMAC",
    "all-over print curved hem t-shirt": "TXMEXICO",
    "all-over print baseball jersey - no piping": "BR-KL",
    "all-over print vietnam football jersey": "FBVN",
    "all-over print satin long-sleeve pajama set": "PJMV",
    "all-over print satin short-sleeve pajama set with long pants": "LPANTSSHIRTV",
    "all-over print women's racerback tank top": "TTOPNU",
    "all-over print women's sport shorts": "QCNU",
    "all-over print youth sport mesh shorts": "QCLUOIKID",
    "all-over print hawaiian shorts": "HWSHORTS",
    "all-over print unisex t-shirtg": "TXG",
    "all-over print short-sleeve hawaiian shirt06": "HWANHDUC06",
    "all-over print pique & mesh football jersey": "FBVAILUOI",
    "all-over print overlap v-neck mesh football crop top jersey": "FBCROPTOP",
    "all-over print youth hawaiian shorts": "QCKIDS",
    "all-over print overlap v-neck mesh football crop top jerseykhop": "FBCRTKHOP",
    "all-over print kids and youth baseball jersey": "BRKIDS",
    "all-over print soccer jersey": "JLSC",
    "all-over print kids and youth baseball jersey - no piping": "BRKIDSKL",
    "all-over print loose sweatpants": "SUONG",
    "all over print premium 3d t-shirtg": "TXG",
    "all-over print kid and youth satin short-sleeve pajama setpant": "SSHORTKIDS",
    "all-over print kid and youth satin short-sleeve pajama setshirt": "SSHIRTKIDS",
    "all-over print kid and youth satin pajama setlpant": "LPANTKIDS",
    "all-over print kid and youth satin pajama setlshirt": "LSHIRTKIDS",
    "double-sided printed polyester flag": "FLAG",
    "all-over print ugly sweater": "UGLY",
    "all-over print hockey jersey": "KCC",
    "all-over print v-neck mesh football crop top jersey": "FBCROPTOPVNECK",
    "all-over print premium hockey jersey": "KCCPREMIUM",
    "all-over print custom shape tie": "CAVAT",
    "all-over print sport mesh shorts": "QCLUOI",
    "graduation stole": "KHAN",
    "kid graduation stole": "KHAN2",
    "all-over print kid satin long-sleeve pajama set": "LPJMSETKID",
    "all-over print kid and youth satin short-sleeve pajama set": "SPJMSETKID",
    "all-over print short-sleeve hawaiian shirtg": "HWGOD",
    "semicircle fence flag": "SEMIFLAG",
    "all-over print lace neck hockey jersey": "HKBUOCDAY",
    "all-over print premium lace neck hockey jersey": "HKPREMIUM",
    "all-over print overlap v-neck mesh hockey jersey": "HKCOTIMLUOI",
    "all-over print polo collar soccer jersey": "PLMXCVNECK",
    "all-over print kids t-shirt": "TSKID",
    "aop youth sport mesh shorts without drawstring": "QCLUOIKHONGDAY",
    "all-over print sport mesh shortsg": "QCLUOIG",
    "aop overlap v-neck mesh football jersey ver 2": "BDLUOI2",
    "all-over print baseball jersey - no pipingdesi": "BR-KLDESI",
    "all-over print football jersey": "FB",
    "all-over print v-neck hockey jersey": "HKCOTIM",
    "all-over print baby jersey bodysuit": "BABYTHREE",
    "all-over print pet jersey": "PETJERSEY",
    "aop double-layer textured satin bandana": "BANDANA",
    "aop single-layer textured satin bandana": "BANDANA2",
    "aop double-layer smooth satin bandana": "BANDANA3",
    "all-over print zip hoodie 230 gsm": "LLY",
    "all-over print premium zip hoodie 270 gsm": "LLY270",
    "all-over print baseball jersey": "BBJER",
    "all-over print hoodie 230 gsm": "OHP",
    "all-over print premium hoodie 270 gsm": "OHP270",
    "all-over print premium men's polo shirt": "PL",
    "all-over print bowling jersey": "PK",
    "all-over print unisex t-shirt": "TX",
    "all over print men tank top": "TTOPTEB",
    "all-over print short-sleeve hawaiian shirt": "HW",
    "all-over print basketball mesh shirts": "TTOPLUOI",
    "all-over print overlap v-neck mesh football jersey": "BDLUOI",
    "all-over print seamless sleeve t-shirt": "TX2",
    "all-over print women's hoodie": "OHPNU",
    "all-over print premium baseball jersey": "PRBBJER",
    "all-over print premium baseball jersey - no pipping": "PRBBJERNP",
    "all-over print kid short-sleeve hawaiian shirt": "HW KIDS",
    "all-over print sweatshirt 230 gsm": "SW",
    "all-over print premium sweatshirt 270 gsm": "SW270",
    "all-over print unisex t-shirtzg": "TXZG2930",
    "all-over print men's tank top": "TTOPVAI",
    "all-over print mesh baseball jersey - no piping": "BBJERNPLUOI",
    "all-over print pocket unisex hawaiian shirt": "HT",
    "all-over print boxy mesh football jersey": "FBCROPTOPBOXY",
};

/** Case-insensitive, trim khoảng trắng thừa. Không khớp → null. */
export function mapProductTypeToCode(type?: string | null): string | null {
    if (!type) return null;
    return PRODUCT_TYPE_CODE_MAP[type.trim().toLowerCase()] ?? null;
}
