version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - ${RABBITMQ_AMQP_PORT}:5672
      - ${RABBITMQ_WEB_PORT}:15672
    volumes:
      - ${RABBITMQ_DATA_PATH}:/var/lib/rabbitmq/
      - ${RABBITMQ_LOG_PATH}:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - printsel

  redis:
    image: redis:alpine
    container_name: 'redis'
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DB}
    entrypoint: ['sh', '-c', 'redis-server --requirepass $$REDIS_PASSWORD']
    networks:
      - printsel

  mongodb:
    image: mongo:6.0
    container_name: 'printsel-mongodb'
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ~/.docker-conf/mongodb/data:/data/db
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
    networks:
      - printsel

networks:
  printsel:
    driver: bridge
